# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basil_dense__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_dense__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

basil_block_dense__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_block_dense__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

basil_ghost__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_ghost__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

basil_block_ghost__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_block_ghost__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

objective_sparse__ <- function(A, r, s, lmda, beta) {
    .Call(`_ghostbasil_objective_sparse__`, A, r, s, lmda, beta)
}

objective_dense__ <- function(A, r, s, lmda, beta) {
    .Call(`_ghostbasil_objective_dense__`, A, r, s, lmda, beta)
}

