# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basil_dense__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_dense__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

basil_block_dense__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_block_dense__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

basil_ghost__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_ghost__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

basil_block_ghost__ <- function(A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads) {
    .Call(`_ghostbasil_basil_block_ghost__`, A, r, s, user_lmdas, max_n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, max_strong_size, max_n_cds, thr, min_ratio, n_threads)
}

objective_sparse__ <- function(A, r, s, lmda, beta) {
    .Call(`_ghostbasil_objective_sparse__`, A, r, s, lmda, beta)
}

objective_dense__ <- function(A, r, s, lmda, beta) {
    .Call(`_ghostbasil_objective_dense__`, A, r, s, lmda, beta)
}

update_group_coeffs__ <- function(L, v, lmda, s, tol = 1e-8, max_iters = 1000L) {
    .Call(`_ghostbasil_update_group_coeffs__`, L, v, lmda, s, tol, max_iters)
}

group_lasso__ <- function(A, groups, group_sizes, s, strong_set, strong_g1, strong_g2, strong_begins, strong_A_diag, lmdas, max_cds, thr, newton_tol, newton_max_iters, rsq, strong_beta, strong_grad, active_set, active_g1, active_g2, active_begins, active_order, is_active) {
    .Call(`_ghostbasil_group_lasso__`, A, groups, group_sizes, s, strong_set, strong_g1, strong_g2, strong_begins, strong_A_diag, lmdas, max_cds, thr, newton_tol, newton_max_iters, rsq, strong_beta, strong_grad, active_set, active_g1, active_g2, active_begins, active_order, is_active)
}

lasso__ <- function(A, s, strong_set, strong_order, strong_A_diag, lmdas, max_cds, thr, rsq, strong_beta, strong_grad, active_set, active_order, active_set_ordered, is_active) {
    .Call(`_ghostbasil_lasso__`, A, s, strong_set, strong_order, strong_A_diag, lmdas, max_cds, thr, rsq, strong_beta, strong_grad, active_set, active_order, active_set_ordered, is_active)
}

