// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_basil__
List fit_basil__(const Eigen::Map<Eigen::MatrixXd> A, const Eigen::Map<Eigen::VectorXd> y, double s, size_t n_knockoffs, size_t n_lambdas, size_t n_lambdas_iter, size_t strong_size, size_t delta_strong_size, size_t n_iters, size_t max_cds, double thr);
RcppExport SEXP _GhostBASIL_fit_basil__(SEXP ASEXP, SEXP ySEXP, SEXP sSEXP, SEXP n_knockoffsSEXP, SEXP n_lambdasSEXP, SEXP n_lambdas_iterSEXP, SEXP strong_sizeSEXP, SEXP delta_strong_sizeSEXP, SEXP n_itersSEXP, SEXP max_cdsSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_knockoffs(n_knockoffsSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_lambdas(n_lambdasSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_lambdas_iter(n_lambdas_iterSEXP);
    Rcpp::traits::input_parameter< size_t >::type strong_size(strong_sizeSEXP);
    Rcpp::traits::input_parameter< size_t >::type delta_strong_size(delta_strong_sizeSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_iters(n_itersSEXP);
    Rcpp::traits::input_parameter< size_t >::type max_cds(max_cdsSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_basil__(A, y, s, n_knockoffs, n_lambdas, n_lambdas_iter, strong_size, delta_strong_size, n_iters, max_cds, thr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GhostBASIL_fit_basil__", (DL_FUNC) &_GhostBASIL_fit_basil__, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_GhostBASIL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
